### ISSUE TITLE
RTX series cards

### ISSUE THREAD

**Issue by MaynardMiner** [duality-solutions/Dynamic-GPU-Miner-Nvidia#1]
Does this miner work with RTX series cards? I am being told that it is closing on start. I have no other reports of failure, but the users with RTX cards.

**Comment by nemosminer** [comment]
@MaynardMiner it works great on RTX 2080 (Tested) on single and 6 x rig

**Comment by MaynardMiner** [comment]
Okay. Thanks. I will pass on.
